name: Deploy (Prod)

on:
  release:
      types: [published]
  workflow_dispatch:

permissions:
    packages: read

env:
    GITHUB_PKG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
    SURGE_DOMAIN: ${{ secrets.SURGE_DOMAIN }}

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install Quasar CLI and Surge
              run: npm i -g @quasar/cli surge
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: quasar build
            - name: Deploy SPA
              run: surge ./dist/spa/ ${{ env.SURGE_DOMAIN }} --token ${{ env.SURGE_TOKEN }}
