export default class APIError extends Error {
    public code: number

    constructor(code?: number, message?: string) {
        code = code ?? 1
        message = message ?? apiErrors[code] ?? 'Unknown error'

        super(message)

        this.code = code
    }
}

export const apiErrors = {
    1: 'General error',
    1001: 'Unknown user',
    1002: 'Unknown guild',
    1003: 'Unknown server',
    1004: 'Unknown message',
    1009: 'Unknown plugin',
    1010: 'Unknown automation',
    1011: 'Unknown custom command',
    1012: 'Unknown interactive message',
    1013: 'Unknown interactive reaction',
    1014: 'Unknown Telegram subscription',
    1015: 'Unknown Twitch subscription',
    1016: 'Unknown YouTube subscription',
    1017: 'Unknown auto-voice',
    1018: 'Unknown bill',
    1019: 'Unknown premium tier',
    1020: 'Unknown payment provider',
    2001: 'Server has no premium',
    2002: 'Automation is already exists',
    2003: 'Custom command is already exists',
    2004: 'Bot must be a guild member',
    2005: 'Telegram subscription is already exists',
    2006: 'Twitch subscription is already exists',
    2007: 'YouTube subscription is already exists',
    2008: 'Auto-voice is already exists',
    2009: 'Server already has premium',
    3001: 'Maximum number of custom commands reached',
    3002: 'Maximum number of premium custom commands reached',
    3003: 'Maximum number of interactive messages reached',
    3004: 'Maximum number of premium interactive messages reached',
    3005: 'Maximum number of interactive reactions reached',
    3006: 'Maximum number of premium interactive reactions reached',
    3007: 'Maximum number of Telegram subscriptions reached',
    3008: 'Maximum number of premium Telegram subscriptions reached',
    3009: 'Maximum number of Twitch subscriptions reached',
    3010: 'Maximum number of premium Twitch subscriptions reached',
    3011: 'Maximum number of YouTube subscriptions reached',
    3012: 'Maximum number of premium YouTube subscriptions reached',
    3013: 'Maximum number of auto-voices reached',
    3014: 'Maximum number of premium auto-voices reached',
    3015: 'Maximum number of premium servers reached',
    4001: 'Unauthorized',
    4002: 'Missing access',
    4003: 'A custom command must contain components',
    4004: 'Custom command name must be unique',
    4005: 'An interactive message cannot be empty',
    4006: 'An interactive message must have components and/or reactions',
    4007: 'Emoji is already used on message',
    4008: 'Single reference cannot be used on another interactive reaction',
    4009: 'You have created too many bills lately',
    4010: 'Invalid automation',
    4011: 'Invalid custom command',
    4012: 'Invalid method of modifying custom command',
    4013: 'Invalid method of modifying interactive message',
    4014: 'Invalid method of modifying interactive reaction',
    4015: 'Invalid method of modifying Telegram subscription',
    4016: 'Invalid method of modifying Twitch subscription',
    4017: 'Invalid method of modifying YouTube subscription',
    4018: 'Invalid method of modifying auto-voice',
    4019: 'You are not a Diamond Subscriber',
    4020: 'You are not a Server Booster on our support server',
    4021: 'Invalid payment',
    5001: 'Cannot get a list of guilds',
    5002: 'Cannot create a custom command',
    5003: 'Cannot update a custom command',
    5004: 'Cannot delete a custom command',
    5005: 'Cannot create an interactive message',
    5006: 'Cannot update an interactive message',
    5007: 'Cannot delete an interactive message',
    5008: 'Cannot add a reaction to a message',
    5009: 'Cannot create a webhook',
    5010: 'Cannot update a webhook',
    5011: 'Cannot delete a webhook',
    5012: 'Cannot retrieve bill payment URL',
    5013: 'Cannot charge a payment',
    5014: 'Cannot charge an uncompleted payment',
    5015: 'Cannot create a Twitch EventSub subscription',
    5016: 'Cannot delete a Twitch EventSub subscription',
    5017: 'Cannot create a YouTube subscription',
    5018: 'Cannot delete a YouTube subscription'
}
