name: Build

on:
  pull_request:
    branches: [main, prod]
  workflow_dispatch:

permissions:
  packages: read
  contents: read

env:
  GH_PKG_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
