name: Build

on:
    pull_request:
        branches: [master]
    workflow_dispatch:

permissions:
    packages: read
    contents: read

jobs:
    build:
        runs-on: self-hosted
        strategy:
            matrix:
                node-version: [18.x, 20.x]

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Set GitHub Packages token
              run: npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
            - run: npm ci
            - run: npm run build
