name: Deploy Application
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

defaults:
  run:
    working-directory: ./Lacuna

jobs:
  deploy:
    runs-on: self-hosted
    
    strategy:
      matrix:
        node-version: [16.14.x]
        
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Clean install dependencies and build
        run: |
          npm install
          npm run build
      - name: Make a env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          envkey_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
          file_name: .env
